JSFLogin-main/src/main/java/com/objectway/stage/backingbeans/BalanceController.java
package com.objectway.stage.backingbeans;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.ResourceBundle;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.objectway.stage.converter.AccountViewConverter;
import com.objectway.stage.converter.ServiceViewConverter;
import com.objectway.stage.model.AccountServiceBean;
import com.objectway.stage.service.AccountService;
import com.objectway.stage.viewbeans.AccountViewBean;

@ManagedBean
@RequestScoped
public class BalanceController {
	private static final Logger logger = LoggerFactory.getLogger(BalanceController.class);
	private static final ServiceViewConverter<AccountServiceBean, AccountViewBean> accountViewConverter = new AccountViewConverter();
	private static final ResourceBundle messages = ResourceBundle.getBundle("messages/messages");

	private Date selectedDate;
	private Date startDate;
	private Date endDate;

	@ManagedProperty("#{accountService}")
	private AccountService accountService;
	@ManagedProperty("#{clientController.selectedAccountBean}")
	private AccountViewBean selectedAccountBean;

	private BigDecimal balance;
	private BigDecimal meanBalance;
	private int deposits;
	private int withdrawals;
	private int meanDeposits;
	private int meanWithdrawals;

	public BalanceController() {
		super();
		selectedDate = new Date();
		startDate = new Date();
		endDate = new Date();
		balance = new BigDecimal(0.0);
		meanBalance = new BigDecimal(0.0);
		deposits = 0;
		withdrawals = 0;
		meanDeposits = 0;
		meanWithdrawals = 0;
	}

	// Getters and setters
	public Date getSelectedDate() {
		return selectedDate;
	}

	public void setSelectedDate(Date selectedDate) {
		this.selectedDate = selectedDate;
	}
	
	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Date getMinDate() {
		return Date.from(selectedAccountBean.getDateIns().atStartOfDay().atZone(ZoneId.systemDefault()).toInstant());
	}
	
	public AccountService getAccountService() {
		return accountService;
	}

	public void setAccountService(AccountService accountService) {
		this.accountService = accountService;
	}

	public AccountViewBean getSelectedAccountBean() {
		return selectedAccountBean;
	}

	public void setSelectedAccountBean(AccountViewBean selectedAccountBean) {
		this.selectedAccountBean = selectedAccountBean;
	}

	public BigDecimal getBalance() {
		return balance;
	}

	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

	public int getDeposits() {
		return deposits;
	}

	public void setDeposits(int deposits) {
		this.deposits = deposits;
	}

	public int getWithdrawals() {
		return withdrawals;
	}

	public void setWithdrawals(int withdrawals) {
		this.withdrawals = withdrawals;
	}
	
	public int getMeanDeposits() {
		return meanDeposits;
	}

	public void setMeanDeposits(int meanDeposits) {
		this.meanDeposits = meanDeposits;
	}

	public int getMeanWithdrawals() {
		return meanWithdrawals;
	}

	public void setMeanWithdrawals(int meanWithdrawals) {
		this.meanWithdrawals = meanWithdrawals;
	}

	public BigDecimal getMeanBalance() {
		return meanBalance;
	}

	public void setMeanBalance(BigDecimal meanBalance) {
		this.meanBalance = meanBalance;
	}
	// End of getters and setters

	public void updateValuesToDate() {
		logger.info("Started BalanceController.updateValuesToDate()");
		LocalDate selectedLocalDate = selectedDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
		if(!selectedLocalDate.isBefore(selectedAccountBean.getDateIns()))
		{
			setBalance(getUpdatedBalance(selectedLocalDate));
			setDeposits(getUpdatedDeposits(selectedLocalDate));
			setWithdrawals(getUpdatedWithdrawals(selectedLocalDate));
			FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, 
					messages.getString("balance.update.successful.message"),
					messages.getString("balance.update.successful.description"));
			FacesContext.getCurrentInstance().addMessage(null, message);
		} else {
			FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_ERROR, 
					messages.getString("balance.update.failed.message"),
					messages.getString("balance.update.failed.description"));
			FacesContext.getCurrentInstance().addMessage(null, message);
		}
	}

	public void getMeanBalanceBetweenDates() {
		if(!startDate.before(getMinDate()) && !endDate.before(getMinDate())) {
			LocalDate startLocalDate = LocalDate.now();
			LocalDate endLocalDate = LocalDate.now();

			if(startDate.before(endDate)) {
				startLocalDate = startDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
				endLocalDate = endDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
			} else {
				startLocalDate = endDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
				endLocalDate = startDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
			}
			
			setMeanBalance(getUpdatedMeanBalance(
					startLocalDate,
					endLocalDate));
			setMeanDeposits(getDepositsBetweenDates(startLocalDate, endLocalDate));
			setMeanWithdrawals(getWithdrawalsBetweenDates(startLocalDate, endLocalDate));
			FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, 
					messages.getString("balance.update.successful.message"),
					messages.getString("balance.update.successful.description"));
			FacesContext.getCurrentInstance().addMessage(null, message);
		} else {
			FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_ERROR, 
					messages.getString("balance.date.invalid.message"),
					messages.getString("balance.date.invalid.description"));
			FacesContext.getCurrentInstance().addMessage(null, message);
		}
	}
	
	public BigDecimal getUpdatedBalance(LocalDate date) {
		logger.info("Started BalanceController.getUpdatedBalance()");
		return accountService.getBalanceToDate(
				accountViewConverter.viewToService(selectedAccountBean), 
				date).setScale(2);
	}

	public BigDecimal getUpdatedMeanBalance(LocalDate from, LocalDate to) {
		logger.info("Started BalanceController.getUpdatedMeanBalance()");
		return accountService.getMeanBalanceToDate(
				accountViewConverter.viewToService(selectedAccountBean), 
				from,
				to).setScale(2);
	}

	public Integer getUpdatedDeposits(LocalDate date) {
		logger.info("Started BalanceController.getUpdatedDeposits()");
		return accountService.getDepositCountToDate(accountViewConverter.viewToService(selectedAccountBean), date);
	}

	public Integer getUpdatedWithdrawals(LocalDate date) {
		logger.info("Started BalanceController.getUpdatedWithdrawals()");
		return accountService.getWithdrawalCountToDate(accountViewConverter.viewToService(selectedAccountBean), date);
	}

	public Integer getDepositsBetweenDates(LocalDate from, LocalDate to) {
		logger.info("Started BalanceController.getUpdatedDeposits()");
		return accountService.getDepositCountBetweenDates(accountViewConverter.viewToService(selectedAccountBean), from, to);
	}

	public Integer getWithdrawalsBetweenDates(LocalDate from, LocalDate to) {
		logger.info("Started BalanceController.getUpdatedWithdrawals()");
		return accountService.getWithdrawalCountBetweenDates(accountViewConverter.viewToService(selectedAccountBean), from, to);
	}
	
	public String homeButton() {
		selectedDate = new Date();
		startDate = new Date();
		endDate = new Date();
		balance = new BigDecimal(0.0);
		deposits = 0;
		withdrawals = 0;
		meanDeposits = 0;
		meanWithdrawals = 0;
		meanBalance = new BigDecimal(0.0);
		return "/secured/welcome?faces-redirect=true";
	}

	public String backButton() {
		selectedDate = new Date();
		startDate = new Date();
		endDate = new Date();
		balance = new BigDecimal(0.0);
		deposits = 0;
		withdrawals = 0;
		meanDeposits = 0;
		meanWithdrawals = 0;
		meanBalance = new BigDecimal(0.0);
		return "/secured/client?faces-redirect=true";
	}
}

JSFLogin-main/src/main/java/com/objectway/stage/backingbeans/ClientController.java
package com.objectway.stage.backingbeans;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.ResourceBundle;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

import org.primefaces.event.SelectEvent;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.objectway.stage.converter.AccountViewConverter;
import com.objectway.stage.converter.ClientViewConverter;
import com.objectway.stage.converter.ServiceViewConverter;
import com.objectway.stage.model.AccountServiceBean;
import com.objectway.stage.model.ClientServiceBean;
import com.objectway.stage.service.AccountService;
import com.objectway.stage.viewbeans.AccountViewBean;
import com.objectway.stage.viewbeans.ClientViewBean;

@ManagedBean
@SessionScoped
public class ClientController {
	private static final Logger logger = LoggerFactory.getLogger(ClientController.class);
	private static final ResourceBundle messages = ResourceBundle.getBundle("messages/messages");
	private static final ServiceViewConverter<ClientServiceBean, ClientViewBean> clientViewConverter = new ClientViewConverter();
	private static final ServiceViewConverter<AccountServiceBean, AccountViewBean> accountViewConverter = new AccountViewConverter();

	private Date selectedDate;
	private AccountViewBean selectedAccountBean;
	private List<AccountViewBean> accounts;
	
	
	@ManagedProperty("#{accountService}")
	private AccountService accountService;
	@ManagedProperty("#{welcomeController}")
	private WelcomeController welcomeController;

	public ClientController() {
		super();
		selectedDate = new Date();
		selectedAccountBean = new AccountViewBean();
		accounts = new ArrayList<>();  
	}

	// getters and setters
	public AccountViewBean getSelectedAccountBean() {
		return selectedAccountBean;
	}

	public void setSelectedAccountBean(AccountViewBean selectedAccountBean) {
		this.selectedAccountBean = selectedAccountBean;
	}

	public List<AccountViewBean> getAccounts() {
		if (FacesContext.getCurrentInstance().getRenderResponse()) {
			updateAccounts();
		}
		return accounts;
	}

	public void setAccounts(List<AccountViewBean> accounts) {
		this.accounts = accounts;
	}
	
	public AccountService getAccountService() {
		return accountService;
	}

	public void setAccountService(AccountService accountService) {
		this.accountService = accountService;
	}
	
	public WelcomeController getWelcomeController() {
		return welcomeController;
	}

	public void setWelcomeController(WelcomeController welcomeController) {
		this.welcomeController = welcomeController;
	}

	public ClientViewBean getSelectedClientBean() {
		return welcomeController.getSelectedClientBean();
	}

	public void setSelectedClientBean(ClientViewBean selectedClientBean) {
		welcomeController.setSelectedClientBean(selectedClientBean);
	}

	public Date getSelectedDate() {
		return selectedDate;
	}

	public void setSelectedDate(Date selectedDate) {
		this.selectedDate = selectedDate;
	}
	// end of getters and setters

	public String openDefaultAccount() {
		logger.info("Started ClientController.openDefaultAccount()");
		AccountViewBean conto = accountViewConverter.serviceToView(
				accountService.addDefaultAccount(clientViewConverter.viewToService(getSelectedClientBean()), 
						selectedDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate()));
		if(conto != null && conto.getClient().equals(getSelectedClientBean())) {
			updateAccounts();
			FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, 
					messages.getString("account.opensuccessful.message"),
					messages.getString("account.opensuccessful.description"));
			FacesContext.getCurrentInstance().addMessage(null, message);
		} else {
			logger.info("Failed to add conto");
			FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_ERROR, 
					messages.getString("account.openfailed.message"),
					messages.getString("account.openfailed.description"));
			FacesContext.getCurrentInstance().addMessage(null, message);
		}
		return "/secured/client";
	}

	public void updateAccounts() {
		logger.info("Started ClientController.updateAccounts()");
		setSelectedAccountBean(new AccountViewBean());
		if(getSelectedClientBean().getCodiceFiscale()!=null && !getSelectedClientBean().getCodiceFiscale().equals("")) {
			logger.info("Searching accounts for client: "+getSelectedClientBean().getName());
			setAccounts(accountViewConverter.serviceListToViewList(
					accountService.findByClient(
							clientViewConverter.viewToService(getSelectedClientBean()))));
			for(AccountViewBean c: accounts) {
				c.setBalance(accountService.getBalanceToDate(accountViewConverter.viewToService(c), LocalDate.MAX));
			}
			logger.info("Retrieved "+accounts.size()+" accounts");
		} else {
			logger.debug("Invalid client\n"+getSelectedClientBean());
		}
	}
	
	public String homeButton() {
		selectedAccountBean = new AccountViewBean();
		return "/secured/welcome?faces-redirect=true";
	}
	
	public String backButton() {
		selectedAccountBean = new AccountViewBean();
		return "/secured/welcome?faces-redirect=true";
	}
	
	// Listeners
	public void onAccountSelect(SelectEvent event) {
		logger.info("Started ClientController.onAccountSelect()");
		selectedAccountBean = (AccountViewBean) event.getObject();
		selectedAccountBean.setClient(getSelectedClientBean());
		String page = "";
		if(isValidAccount(selectedAccountBean)) {
			logger.debug("Account is valid\n" + getSelectedClientBean());
			page = "/secured/transactions?faces-redirect=true";
		} else {
			logger.debug("Account is not valid\n" + getSelectedClientBean());
			page = "/secured/client";
		}
		FacesContext context = FacesContext.getCurrentInstance();
		context.getApplication().getNavigationHandler().handleNavigation(context, null, page);
	}
	// End of listeners

	// Validators
	public boolean isValidAccount(AccountViewBean c) {
		if(c != null && 
		   c.getBalance()!=null && 
		   c.getDateIns()!=null) {
			return true;
		}
		return false;
	}
	// End of validators
}

JSFLogin-main/src/main/webapp/secured/balance.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<title>#{msg['welcome']}</title>
	<style>
html, body {
	width: 100%;
	height: 100%;
	margin: 0;
}

#content {
	padding-top: 5%;
	padding-left: 20%;
	padding-right: 20%;
}

#content .ui-panel {
	margin: 1em;
	margin-bottom: 2em;
}

.ui-panel {
	align: center;
}

.ui-panel-titlebar {
	text-align: center;
}

#balanceForm #meanBalanceForm {
	margin: auto;
}

#navbar button {
	border: none;
}
</style>
</h:head>

<f:event listener="#{loginController.checkLogin}" type="preRenderView" />

<h:body>
	<div id="navbar">
		<h:form>
			<p:toolbar id="toolbar">
				<f:facet name="left">
					<p:commandButton value="#{msg.home}"
						action="#{balanceController.homeButton}" />
					<p:commandButton value="#{msg.back}"
						action="#{balanceController.backButton}" />
				</f:facet>

				<f:facet name="right">
					<p:commandButton value="#{msg.logout}"
						action="#{loginController.logout}" />
				</f:facet>
			</p:toolbar>
		</h:form>
	</div>

	<p:messages id="balanceErrMessages">
		<p:autoUpdate />
	</p:messages>

	<div id="content">
		<p:panel header="#{msg['balance.panel']}">
			<h:form id="balanceForm">
				<div>
					<h:panelGrid columns="3" cellpadding="2">
						<h:outputLabel for="dateinput" style="font-weight: bold"
							value="#{msg['transaction.creationDate']}" />
						<p:datePicker id="dateinput" pattern="yyyy-MM-dd"
							value="#{balanceController.selectedDate}" required="true"
							mindate="#{balanceController.minDate}">
						</p:datePicker>

						<p:commandButton update="balanceErrMessages"
							action="#{balanceController.updateValuesToDate}"
							value="#{msg['balance.button']}" validateClient="true"
							ajax="false" />
					</h:panelGrid>
				</div>

				<h:panelGrid columns="2" cellpadding="2">
					<h:outputLabel for="balanceText" style="font-weight: bold"
						value="#{msg['account.balance']}" />
					<h:outputText id="balanceText" value="#{balanceController.balance}">
						<f:convertNumber type="currency" currencySymbol="€" />
					</h:outputText>

					<h:outputLabel for="depositText" style="font-weight: bold"
						value="#{msg['deposits']}" />
					<h:outputText id="depositText"
						value="#{balanceController.deposits}" />

					<h:outputLabel for="withdrawalText" style="font-weight: bold"
						value="#{msg['withdrawals']}" />
					<h:outputText id="withdrawalText"
						value="#{balanceController.withdrawals}" />
				</h:panelGrid>
			</h:form>
		</p:panel>
		
		<br/>

		<p:panel header="#{msg['balance.panel.mean']}">
			<h:form id="meanBalanceForm">
				<div>
					<h:panelGrid columns="5" cellpadding="2">
						<h:outputLabel for="startdateinput" style="font-weight: bold"
							value="#{msg['transaction.startDate']}" />
						<p:datePicker id="startdateinput" pattern="yyyy-MM-dd"
							value="#{balanceController.startDate}" required="true"
							mindate="#{balanceController.minDate}">
						</p:datePicker>

						<h:outputLabel for="enddateinput" style="font-weight: bold"
							value="#{msg['transaction.endDate']}" />
						<p:datePicker id="enddateinput" pattern="yyyy-MM-dd"
							value="#{balanceController.endDate}" required="true"
							mindate="#{balanceController.minDate}">
						</p:datePicker>
					<p:commandButton update="balanceErrMessages"
						action="#{balanceController.getMeanBalanceBetweenDates}"
						value="#{msg['balance.button']}" validateClient="true"
						ajax="false" />
					</h:panelGrid>
				</div>

				<h:panelGrid columns="2" cellpadding="2">
					<h:outputLabel for="meanBalanceText" style="font-weight: bold"
						value="#{msg['balance.mean.todate']}" />
					<h:outputText id="meanBalanceText"
						value="#{balanceController.meanBalance}">
						<f:convertNumber type="currency" />
					</h:outputText>

					<h:outputLabel for="meanDepositText" style="font-weight: bold"
						value="#{msg['deposits']}" />
					<h:outputText id="meanDepositText"
						value="#{balanceController.meanDeposits}" />

					<h:outputLabel for="meanWithdrawalText" style="font-weight: bold"
						value="#{msg['withdrawals']}" />
					<h:outputText id="meanWithdrawalText"
						value="#{balanceController.meanWithdrawals}" />
				</h:panelGrid>
			</h:form>
		</p:panel>

	</div>
</h:body>
</html>

JSFLogin-main/src/main/webapp/secured/client.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<title>#{msg['welcome']}</title>
	<style>
body {
	margin: 0;
}

.ui-grid {
	border: none;
}

#navbar button {
	border: none;
}

#content {
	padding-top: 5%;
	padding-left: 20%;
	padding-right: 20%;
}

#content .ui-panel {
	margin: 1em;
	margin-bottom: 2em;
}
</style>
</h:head>

<f:event listener="#{loginController.checkLogin}" type="preRenderView" />

<h:body>
	<p:growl id="accountErrMessages" showDetail="true"
		skipDetailIfEqualsSummary="true" />

	<h:form id="navbar">
		<p:toolbar>
			<f:facet name="left">
				<p:commandButton value="#{msg.home}"
					action="#{clientController.homeButton}" />
				<p:commandButton value="#{msg.back}"
					action="#{clientController.backButton}" />
			</f:facet>

			<f:facet name="right">
				<p:commandButton value="#{msg.logout}"
					action="#{loginController.logout}" />
			</f:facet>
		</p:toolbar>
	</h:form>

	<div id="content">
		<p:panel header="#{msg['client.info']}">
			<h:panelGrid columns="2" cellpadding="2">
				<h:outputLabel for="nameoutput" value="#{msg.name} "
					style="font-weight: bold" />
				<h:outputText id="nameoutput"
					value="#{welcomeController.selectedClientBean.name}"></h:outputText>

				<h:outputLabel for="surnameoutput" value="#{msg.surname} "
					style="font-weight: bold" />
				<h:outputText id="surnameoutput"
					value="#{welcomeController.selectedClientBean.surname}"></h:outputText>

				<h:outputLabel for="codiceoutput" value="#{msg.codice} "
					style="font-weight: bold" />
				<h:outputText id="codiceoutput"
					value="#{welcomeController.selectedClientBean.codiceFiscale}"></h:outputText>
			</h:panelGrid>
		</p:panel>

		<p:panel header="#{msg['account.add']}">
			<h:form>
				<h:outputLabel for="dateinput"
					value="#{msg['account.creationDate']}" />
				<p:datePicker id="dateinput" pattern="yyyy-MM-dd"
					value="#{clientController.selectedDate}" required="true">
				</p:datePicker>

				<p:commandButton update="accountErrMessages"
					action="#{clientController.openDefaultAccount}"
					value="#{msg['account.add']}" validateClient="true" ajax="false" />
			</h:form>
		</p:panel>

		<p:panel id="accounts" header="#{msg['account.list']}">
			<h:form>
				<p:dataTable id="contilist" var="account"
					value="#{clientController.accounts}" paginator="true"
					paginatorAlwaysVisible="false" rows="10">
					<p:column headerText="#{msg['account.balance']}"
						style="text-align: center">
						<h:outputText value="#{account.balance}">
							<f:convertNumber type="currency" currencySymbol="€"/>
						</h:outputText>
					</p:column>
					<p:column headerText="#{msg['account.creationDate']}"
						style="text-align: center">
						<h:outputText value="#{account.dateIns}" />
					</p:column>
					<p:column headerText="#{msg['account.operations']}" colspan="2"
						style="text-align: center">
						<p:panelGrid id="buttonrow" columns="2" layout="grid">
							<p:commandButton action="transactions?faces-redirect=true"
								value="#{msg['transaction.list.button']}">
								<f:setPropertyActionListener value="#{account}"
									target="#{clientController.selectedAccountBean}" />
							</p:commandButton>
							<p:commandButton action="balance?faces-redirect=true"
								value="#{msg['balance.check.button']}">
								<f:setPropertyActionListener value="#{account}"
									target="#{clientController.selectedAccountBean}" />
							</p:commandButton>
						</p:panelGrid>
					</p:column>
				</p:dataTable>
			</h:form>
		</p:panel>
	</div>
</h:body>
</html>

JSFLogin-main/src/main/webapp/secured/transactions.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<title>#{msg['welcome']}</title>
	<style>
body {
	margin: 0;
}

#navbar button {
	border: none;
}

#content {
	padding: 1em;
}

#content .ui-panel {
	margin: 1em;
}
</style>
</h:head>

<f:event listener="#{loginController.checkLogin}" type="preRenderView" />

<h:body>
	<p:growl id="accountErrMessages" showDetail="true"
		skipDetailIfEqualsSummary="true" />

	<h:form id="navbar">
		<p:toolbar>
			<f:facet name="left">
				<p:commandButton value="#{msg.home}"
					action="#{transactionsController.homeButton}" />
				<p:commandButton value="#{msg.back}"
					action="#{transactionsController.backButton}" />
			</f:facet>

			<f:facet name="right">
				<p:commandButton value="#{msg.logout}"
					action="#{loginController.logout}" />
			</f:facet>
		</p:toolbar>
	</h:form>

	<div id="content">
		<p:panel header="#{msg['transaction.add']}">
			<h:form>
				<h:panelGrid columns="2" cellpadding="2">
					<h:outputLabel for="typeinput"
						value="#{msg['transaction.type.deposit']}" />
					<p:selectBooleanCheckbox id="typeinput"
						value="#{transactionsController.transactionBean.deposit}" />

					<h:outputLabel for="amountinput"
						value="#{msg['transaction.amount']}" />
					<p:inputNumber id="amountinput" placeholder="0.00"
						decimalPlaces="2"
						value="#{transactionsController.transactionBean.amount}"
						required="true"/>

					<h:outputLabel for="dateinput"
						value="#{msg['transaction.creationDate']}" />
					<p:datePicker id="dateinput" pattern="yyyy-MM-dd"
						value="#{transactionsController.currentDate}" required="true"
						mindate="#{transactionsController.minDate}">
					</p:datePicker>

					<p:commandButton update="transactionErrMessages"
						action="#{transactionsController.addTransaction}"
						value="#{msg['transaction.add.button']}" validateClient="true"
						ajax="false" />
				</h:panelGrid>
			</h:form>
		</p:panel>

		<p:panel id="movements" header="#{msg['transaction.list']}">
			<h:form id="transactions">
				<p:dataTable id="transactionlist" var="transaction"
					value="#{transactionsController.transactions}"
					style="text-align: center">
					<p:column headerText="#{msg['transaction.type']}">
						<h:outputText value="#{transaction.transactionType}" />
					</p:column>
					<p:column headerText="#{msg['transaction.amount']}">
						<h:outputText value="#{transaction.amount}" >
							<f:convertNumber type="currency" currencySymbol="€" />
						</h:outputText>
					</p:column>
					<p:column headerText="#{msg['transaction.creationDate']}">
						<h:outputText id="date" value="#{transaction.dateIns}"/>
					</p:column>
				</p:dataTable>
			</h:form>
		</p:panel>
	</div>
</h:body>
</html>